-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 16:11:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto_Finanzas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Proyecto_Finanzas` ;

-- -----------------------------------------------------
-- Schema Proyecto_Finanzas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_Finanzas` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto_Finanzas` ;

-- -----------------------------------------------------
-- Table `Proyecto_Finanzas`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Finanzas`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rol` ENUM('client', 'admin') NOT NULL DEFAULT 'client',
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Proyecto_Finanzas`.`income_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Finanzas`.`income_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Proyecto_Finanzas`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Finanzas`.`income` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL DEFAULT 0,
  `income_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `coment` VARCHAR(200) NULL,
  `income_type_id` INT UNSIGNED NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_income_income_type_idx` (`income_type_id` ASC) VISIBLE,
  INDEX `fk_income_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_income_income_type`
    FOREIGN KEY (`income_type_id`)
    REFERENCES `Proyecto_Finanzas`.`income_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_income_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Proyecto_Finanzas`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Proyecto_Finanzas`.`expense_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Finanzas`.`expense_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Proyecto_Finanzas`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_Finanzas`.`expense` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL DEFAULT 0,
  `expense_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `coment` VARCHAR(200) NULL,
  `id_type` INT NOT NULL,
  `expense_type_id` INT UNSIGNED NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_expense_expense_type1_idx` (`expense_type_id` ASC) VISIBLE,
  INDEX `fk_expense_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_expense_expense_type1`
    FOREIGN KEY (`expense_type_id`)
    REFERENCES `Proyecto_Finanzas`.`expense_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expense_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Proyecto_Finanzas`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
